### ISSUE TITLE
FlowNode doesn't display well in dark mode

### ISSUE THREAD

**Issue by dsherret** [dsherret/ts-ast-viewer#138]
Just noticed this:

![image](https://github.com/dsherret/ts-ast-viewer/assets/1609021/ac2fe26d-64a1-4c4a-9ede-22f027d7d239)

cc @danvk in case you have any tips for how to fix this. I looked briefly at how to change the colours in the rendered svg, but gave up.

**Comment by danvk** [comment]
Interesting. You probably have to set a property on the nodes in the dot
spec. I can take a look at this tomorrow. I guess it’ll have to be tomorrow
night? :p

**Comment by dsherret** [comment]
If you could help whenever you find the time that would be great. There's no rush on this. I tried a bunch of stuff and it didn't work. Also had trouble searching for how to do this 😅
