### ISSUE TITLE
Using the app freezes the browser

### ISSUE THREAD

**Issue by karol-majewski** [dsherret/ts-ast-viewer#19]
Hello and thank you for your work. I've just watched the recording of your talk at TSConf and I must say — it was one of the best.

I've noticed it's quite easy to get the AST Viewer to crash, along with the browser.

1. Go to https://ts-ast-viewer.com/
2. Type `const document = window.document`.
3. Click the `PropertyAccessExpression` immediately.

What happens:

1. CPU usage goes to 100%
2. Memory usage explodes.

Chrome debugger halts the execution with the message:

> Paused before potential out-of-memory crash

Tried on Chrome 66.

I've made a recording if that helps:

![ast-viewer](https://user-images.githubusercontent.com/20233319/39676825-2285b7a8-5171-11e8-823f-da35f48a409a.gif)

**Comment by dsherret** [comment]
Hey @karol-majewski, thanks I'm glad you enjoyed the talk 😄

I just looked into this and the reason it goes up so crazy and eventually crashes is because there's a lot of information on `window` to display. I'm going to have to solve this by lazily loading the items in the tree view on expand. Right now I'm populating everything at once. Thanks for reporting this!

**Comment by karol-majewski** [comment]
Maybe it's worth mentioning that you don't necessarily have to mess with `window` in order to crash it. The first time I noticed it was when I wrote:

```ts
const { stringify } = JSON;
```

Then I clicked around the explorer a bit.

**Comment by dsherret** [comment]
Thanks, yeah worth mentioning. There's a lot of information on the `JSON` identifier's symbol as well.

**Comment by dsherret** [comment]
Ok, should be much faster now and shouldn't freeze due to this scenario. Let me know if this is still an issue if it is (might need to ctrl+f5 the website due to caching). Thanks again for reporting it!

Fixing this made me realize I really need to fix #12.

**Comment by karol-majewski** [comment]
@dsherret I couldn't make it crash. Nicely done!

**Comment by mszu** [comment]
Hi, I wanted to chime in and say both thank you for putting this together and that I'm still running into this issue.

Providing the following input:
```typescript
interface Asdf {
    a: string[];
}
```

and clicking on the `PropertySignature` tree item (or its immediate child `Identifier`) produces the same recursion error output as above (tested in FF 60.0 and Chrome 66.0.3359.181 on Mac OS 10.12.6).

**Comment by dsherret** [comment]
Thanks @mszu! Should be fixed now. I missed that scenario the first time around.
