### ISSUE TITLE
Highlight or outline selected node in code editor

### ISSUE THREAD

**Issue by dsherret** [dsherret/ts-ast-viewer#21]
It should highlight the selected node from `.getStart(true)` to `end`.

Most likely this would be better with an outline. If only a highlight is easy then don't make it highlight when the source file is the selected node.

**Comment by shashank-srikant** [comment]
(github's beta of showing up 'related issues' seems to work great. saved me from submitting a copy of this)
this would indeed enhance usability.

so would having this feature the other way around as well -- the AST nodes lighting up when having the moving over the mouse over a line of code; similar to the experience provided by any browser's element-inspection tool.
