### ISSUE TITLE
TSX support

### ISSUE THREAD

**Issue by seanf** [dsherret/ts-ast-viewer#3]
I was able to do this simply by changing `ts.ScriptKind.Unknown` to `ts.ScriptKind.TSX`, but I don't know what ramifications that might have (because I don't know what `ts.ScriptKind.Unknown` does).

https://github.com/dsherret/ts-ast-viewer/blob/4a1f15081b4db246523fcd22c30516c344c47abc/src/App.tsx#L42

**Comment by dsherret** [comment]
Hey @seanf, that would be a good change. I looked through the parser and I believe the only drawback will be that it won't support `<string>value`-like type assertions. For the time being, I believe supporting JSX is more important than those assertions. In the future, I'll add a checkbox option to disable or enable tsx similar to how the typescript playground has an options area.

If you're able, could you submit a pull request with your change? Maybe also give the file a `.tsx` extension (on that same line of code). If not, I'll make this change soon.

**Comment by seanf** [comment]
PR for this: #4

**Comment by dsherret** [comment]
Thanks Sean! I opened #5 based on this discussion.

I'll do a release soon... there's one caching issue I want to figure out (for some reason after doing a release the entire site will break until a hard refresh is done... must be something to do with github pages)

**Comment by dsherret** [comment]
Ok this is released. Just do a hard refresh a couple of times...
