### ISSUE TITLE
Incorrect serialization of Symbol.exports

### ISSUE THREAD

**Issue by ajafff** [dsherret/ts-ast-viewer#32]
Code:
```ts
enum Foo {
  Bar
}
```

Select the EnumDeclaration. **Symbol** will display the serialized Symbol of that declaration. However, `exports` is always displayed as empty object (possibly because `JSON.stringify` is used which doesn't know how to handle `Map`?)

**Comment by dsherret** [comment]
Thanks for reporting! It's because it's using `Object.keys`, but it should use `.keys()` for maps.

**Comment by dsherret** [comment]
@ajafff Fixed and released.

Btw, check out the developer console to easily get access to the objects (just added this feature). Use `selectedNode`, `sourceFile`, `symbol`, `type`, `program`, and `typeChecker`. I'll have to add a help dialog that outlines this feature.

**Comment by ajafff** [comment]
@dsherret that sounds amazing
