### ISSUE TITLE
Crash when importing from external module

### ISSUE THREAD

**Issue by ajafff** [dsherret/ts-ast-viewer#36]
```
Something went wrong
TypeError: Cannot read property 'kind' of undefined
```

Each of the lines below triggers the crash
```ts
import * as foo from 'foo';
import foo from 'foo';
import {foo} from 'foo';
export * from 'foo';
```

**Comment by dsherret** [comment]
Thanks for reporting once again, @ajafff! I added a test so this shouldn't happen again in the future. This will be released once the CI builds successfully.
