### ISSUE TITLE
suggestion : highlight selected AST Node

### ISSUE THREAD

**Issue by WanderWang** [dsherret/ts-ast-viewer#38]
I have a similar private project such as ts-ast-viewer . I have a suggesion for you , please hightlight the SourceFile Text when selected ast node , such as :  

![image](https://user-images.githubusercontent.com/2238280/50811152-2a507600-1348-11e9-8f5b-19f8f581746f.png)

When I click "ClassKeyword" in ast TreeView, the sourcefile text view will be highlighted

**Comment by dsherret** [comment]
Hey @WanderWang, thanks for the suggestion, but this is captured in #21. Yes, it would be incredibly useful and it would be nice if this was implemented soon :)
