### ISSUE TITLE
Generate TypeScript Compiler API template code

### ISSUE THREAD

**Issue by septs** [dsherret/ts-ast-viewer#40]
from AST generate **tsc** code

![image](https://user-images.githubusercontent.com/3842474/54433805-acee1b00-4767-11e9-81b1-1beec9a4b7c5.png)

```typescript
const example: number = 1;

// convert to the code

ts.createVariableStatement(
    undefined,
    ts.createVariableDeclarationList(
        [
            ts.createVariableDeclaration(
                ts.createIdentifier("example"),
                ts.createKeywordTypeNode(ts.SyntaxKind.NumberKeyword),
                ts.createLiteral("1"),
            ),
        ],
        ts.NodeFlags.Const,
    ),
);
```

--------

TypeScript Compiler a.k.a tsc

**Comment by dsherret** [comment]
It would be very nice to do that, but it would take a lot of work. One issue though is the compiler doesn't have factory functions for every node so the end solution would be incomplete (perhaps comments could be inserted for when that happens).

If anything, I think that could be started in a separate library if someone wanted to take that on and then I could incorporate it here.

**Comment by ajafff** [comment]
This already exists as a separate tool: https://github.com/HearTao/ts-creator

**Comment by dsherret** [comment]
@ajafff thanks! That could definitely be used here.

**Comment by dsherret** [comment]
This is implemented via a right click menu on the editor. Thanks a lot @septs for recommending this!

Unfortunately, I didn't implement this on a per node level because the ts-creator dependency relies on a specific version of the typescript compiler... so this will just always do the full source file text.

![output](https://user-images.githubusercontent.com/1609021/54503846-7222e900-4907-11e9-9669-77ee725b709b.gif)

**Comment by dsherret** [comment]
This isn't very discoverable though. I'll change it to be a checkbox in the options.

**Comment by dsherret** [comment]
This code is now using https://github.com/dsherret/ts-factory-code-generator-generator which will pre-generate the code to generate this code depending on the selected compiler version.
