### ISSUE TITLE
Expose current selected node into global variable

### ISSUE THREAD

**Issue by cevek** [dsherret/ts-ast-viewer#49]
It would be very helpful to investigate typescript type nodes in dev tools console

**Comment by dsherret** [comment]
Hey @cevek, yup, that's already a hidden feature :)

https://github.com/dsherret/ts-ast-viewer/blob/master/docs/about.md#interacting-with-compiler-objects

**Comment by cevek** [comment]
@dsherret Oh, nice! Thanks!
