### ISSUE TITLE
Many errors related to not being able to find lib files

### ISSUE THREAD

**Issue by dsherret** [dsherret/ts-ast-viewer#56]
Will look into this later:

![image](https://user-images.githubusercontent.com/1609021/62483967-0db5d880-b787-11e9-8ef2-7097e900990e.png)

**Comment by dsherret** [comment]
I made this a bit better by disabling syntactic diagnostics in addition to semantic ones, but for some reason it still appears when doing:

```ts
class MyClass {
    prop: string;
}
```

...and clicking on `string`. Would be nice to get this working with syntactic diagnostics.

**Comment by Gerrit0** [comment]
This bit me yesterday - I'd used the tool before you disabled syntactic diagnostics so was used to errors showing up when I did something bad. Adding this to my todo list to look into.

**Comment by dsherret** [comment]
@Gerrit0 yeah, I was kind of hoping this would just be fixed after a while by waiting and updating the dependencies, but that hasn't happened. Might be worth it to try out https://github.com/SurenAt93/monaco-react instead of monaco-editor-react as monaco-editor-react requires webpack, but this project uses create-react-app (I have a workaround to make it work without it)
