### ISSUE TITLE
The bottom-left window's scroll bar is flickering

### ISSUE THREAD

**Issue by lazarljubenovic** [dsherret/ts-ast-viewer#57]
It seems like it's refreshing all the time, in every frame. Also when I right click, I see the context menu for one frame, and then it's gone. If you can't see it, I can record a video. Using the latest Chrome.

**Comment by dsherret** [comment]
I've noticed that too, but have been too lazy to look into it. I just upgraded to the latest react-monaco-editor and it seems to not be as bad as before.

**Comment by dsherret** [comment]
Fixed by using exact pixel values for the initial height rather than a percentage. I guess monaco editor would resize and some rounding error would keep it increasing in size.

Also implemented @cancerberoSgx's refreshing from his answer here: https://stackoverflow.com/a/50978186/188246
