### ISSUE TITLE
Show internals with different text colour

### ISSUE THREAD

**Issue by dsherret** [dsherret/ts-ast-viewer#65]
Perhaps when the internals are shown they should have a text colour of red.

**Comment by jackkoppa** [comment]
Just wanted to say thanks for this - I was having trouble figuring out why I could see `checkJsDirective` here: https://ts-ast-viewer.com/#code/FAehAIAEBcGcFoDGALApog1sRB7AdrNOAIbgC84A5JcEA 

but TypeScript was yelling at me for trying to access it in code, as I described here: https://github.com/vuejs/vetur/pull/1439/files#r329721435

(still trying to figure out my solution, but it's easier to move on to the next approach now; thanks!)

**Comment by dsherret** [comment]
No problem! It looks like the type `CheckJsDirective` is in the public API: https://github.com/microsoft/TypeScript/blob/96f01227d4f300ad85e5e470595b5c7bd96d9304/lib/typescript.d.ts#L1566

...but it's not accessible any way because the property is private. Most likely that property should be made public. You may want to open an issue about this on TypeScript's repo.
