### ISSUE TITLE
typescript@next is not up to date

### ISSUE THREAD

**Issue by ajafff** [dsherret/ts-ast-viewer#70]
When selecting `@next` it uses `v3.8.0-dev.20191214`.
As of writing `typescript@next` is `v2.8.0-20191231`.

**Comment by dsherret** [comment]
Yeah, it's because the CI won't pass... been getting emails about it for a while. I had been trying to figure out the magic configuration to get cypress to pass on the CI and last night I figured it out by running it on node version 11.

**Comment by dsherret** [comment]
Fixed. I got it to finally build.
