### ISSUE TITLE
Uncaught Error: Debug Failure. Unexpected node.

### ISSUE THREAD

**Issue by Gerrit0** [dsherret/ts-ast-viewer#72]
Reproduction:

Paste this into the viewer:
```ts
'use strict'

const fs = require('fs')
const os = require('os')
const path = require('path')
const nanoid = require('nanoid')

/**
 * Temporary folder
 *
 * @param {(d: string) => string} transform - Transform function to add prefixes or sufixes to the unique id
 * @returns {string} - Full real path to a temporary folder
 */
const tempdir = (transform = d => d) => {
  const osTmpDir = fs.realpathSync(os.tmpdir())
  return path.join(osTmpDir, transform(nanoid()))
}

module.exports = {
  tempdir
}
```

Hit CTRL+A to select all
Error shows up in the console
![image](https://user-images.githubusercontent.com/19329837/77986897-813bc580-72d5-11ea-9edc-7cb672864621.png)

Might have time to look at this this weekend, but wanted to document it when I noticed it.

**Comment by dsherret** [comment]
Same problem happens in the typescript playground: https://www.typescriptlang.org/play/

**Comment by Gerrit0** [comment]
I'll close this in favor of https://github.com/microsoft/TypeScript-Website/issues/462, I spent a bit of time trying to figure out where it's coming from but would probably need a few hours of digging... Orta actually understands this stuff so I'll leave it to him :)
