### ISSUE TITLE
Fix build for TS 4.0

### ISSUE THREAD

**Issue by dsherret** [dsherret/ts-ast-viewer#79]
Looks like TypeScript renaming a property on the TupleType node broke a lot of stuff.

Waiting on https://github.com/facebook/create-react-app/issues/9515 to be fixed.

**Comment by dsherret** [comment]
I should just drop create react app eventually. Now waiting on these two new bugs:

* https://github.com/facebook/create-react-app/issues/9868
* https://github.com/facebook/create-react-app/issues/9874

**Comment by dsherret** [comment]
Ended up just implementing #82. create-react-app does not seem to value TypeScript support.

**Comment by ChristianIvicevic** [comment]
Offtopic banter: Just saw your issue referenced over in CRA, the mentioned fix in one of the issues, especially the comment at the end of the post are pure gold: https://github.com/facebook/create-react-app/issues/9868#issuecomment-715418383

Unfortunately create-react-app will most likely not consider Typescript a first-class citizen for a long time...

**Comment by dsherret** [comment]
@ChristianIvicevic that's kind of funny, but also disappointing 😐
