### ISSUE TITLE
Improve indentation for leaf/complex items

### ISSUE THREAD

**Issue by LinqLover** [dsherret/ts-ast-viewer#92]
Here is an example:

![image](https://user-images.githubusercontent.com/38782922/134734217-26084ccf-6077-4498-94fd-c614c8557491.png)

These items are actually siblings, but the inequal indentation makes them look rather as if the second item was a child of the first item. It might be helpful if these indentations could be aligned, i.e., the collapse icon could be displayed offset. :-)

**Comment by dsherret** [comment]
Thanks! I see your point. It is fixed now.

**Comment by LinqLover** [comment]
Very nice, thank you!
