### ISSUE TITLE
FlowNode section display wrong node

### ISSUE THREAD

**Issue by wizardnet972** [dsherret/ts-ast-viewer#98]
`FlowNode` does not change when I hover nodes in the code panel.

```
const COMPONENTS = [bar, baz];
const DIRECTIVES = [bak, bad];

const foo = {
  components: [...COMPONENTS],
  directives: [...DIRECTIVES]
}
```

When I hover `components`: (see the red arrow) should display `COMPONENTS` instead of `DIRECTIVES`.

![image](https://user-images.githubusercontent.com/4997825/169857940-d3242d8d-d29c-4b40-b454-5044ce0f26cd.png)

[ts-ast-viewer.com](https://ts-ast-viewer.com/#code/MYewdgzgLgBAwgeQLIAUEDkCi6AqBlGAXhgG0AjAQwCcAaGSgLwF0BuAKFElgBEBJAJUxwcvAGqYCxchQDWdSgBNWbDuGgwAZiBBEYAbzYwYoALYAHcAFMwUCAC5SAOmeJUGbPiY1DMBQEsqS2AoPwA3S3snZz5BYTEJJjYAXyA)

**Comment by danvk** [comment]
That's not how flow nodes work. The flow node of a node is the previous thing that executed. So the flow node for `components` (lowercase) is `const DIRECTIVES = [bak, bad]`. The TS AST Viewer is showing the correct thing. See #134.
