### ISSUE TITLE
TypeScript 4.7

### ISSUE THREAD

**Issue by lgrammel** [dsherret/ts-ast-viewer#99]
I saw that [ts-ast-viewer.com](https://ts-ast-viewer.com) supports TypeScript 4.7 and tried to find the corresponding code here. However, the repository seems to be using TypeScript `4.5.4`. Is it currently in sync with ts-ast-viewer.com?

**Comment by dsherret** [comment]
Yes, it's in sync. The website gets automatically built and deployed once a day updating to the latest versions of TypeScript.

- https://github.com/dsherret/ts-ast-viewer/blob/main/scripts/addTypeScriptVersions.ts
- https://github.com/dsherret/ts-ast-viewer/commits/gh-pages

**Comment by lgrammel** [comment]
Thanks! 

Does this also affect the lib files ( https://github.com/dsherret/ts-ast-viewer/tree/main/site/src/resources/libFiles/typescript )? 

(I'm asking because I'm looking for a mechanism to generate the lib filese in your format for TS 4.7)

**Comment by dsherret** [comment]
Yes. I think those files just exist in the repo for development purposes. The lib files are created automatically here: https://github.com/dsherret/ts-ast-viewer/blob/main/scripts/copyLibFiles.ts

**Comment by lgrammel** [comment]
Perfect - I ran `yarn run updateCompilerFiles` and it created the files that I was looking for. Thanks for creating ts-ast-viewer, I use it pretty much every day and it's great!
